ocean:
  eos:
    config_eos_type: linear
  eos_linear:
    config_eos_linear_alpha: 0.2
    config_eos_linear_beta: 0.01
    config_eos_linear_Tref: 5.0

mpas-ocean:
  time_management:
    config_run_duration: 0010_00:00:00
  hmix_del4:
    config_use_mom_del4: true
    config_mom_del4: 2.0e14
  frazil_ice:
    config_use_frazil_ice_formation: true
  cvmix:
    config_use_cvmix_convection: true
    config_use_cvmix_shear: true
    config_cvmix_shear_mixing_scheme: KPP
    config_use_cvmix_kpp: true
    config_cvmix_kpp_matching: MatchBoth
    config_cvmix_kpp_interpolationOMLType: cubic
  streams:
    KPP_testing: {}
