ocean:
  time_management:
    config_run_duration: 0005_00:00:00
  hmix_del4:
    config_use_mom_del4: false
  cvmix:
    config_cvmix_background_diffusion: 0.0
    config_use_cvmix_convection: false
    config_use_cvmix_shear: false
  eos:
    config_eos_type: linear
  eos_linear:
    config_eos_linear_beta: 0.01
  forcing:
    config_use_bulk_wind_stress: true

mpas-ocean:
  bottom_drag:
    config_implicit_constant_bottom_drag_coeff: 0.0
  frazil_ice:
    config_use_frazil_ice_formation: false
  cvmix:
    config_cvmix_background_scheme: constant
    config_use_cvmix_kpp: false
  tracer_forcing_activeTracers:
    config_use_activeTracers_surface_bulk_forcing: false
    config_use_activeTracers_surface_restoring: false
    config_use_activeTracers_interior_restoring: false
  streams:
    mesh:
      filename_template: initial_state.nc
    input:
      filename_template: initial_state.nc
    restart: {}
    KPP_testing: {}
    mixedLayerDepthsOutput:
      contents:
      - xtime
      - dThreshMLD
      - tThreshMLD
    output:
      type: output
      filename_template: output.nc
      output_interval: 0000_00:00:01
      clobber_mode: truncate
      contents:
      - tracers
      - xtime
      - daysSinceStartOfSim
      - zMid
      - zTop
      - density
      - normalVelocity
      - velocityZonal
      - velocityMeridional
      - layerThickness
      - kineticEnergyCell
      - relativeVorticityCell
    forcing_data:
      type: input
      filename_template: forcing.nc
      input_interval: initial_only
      contents:
      - windStressZonal
      - windStressMeridional
