ocean:
  time_management:
    config_stop_time: none
    config_run_duration: 0002_00:00:00
  time_integration:
    config_dt: 0000_00:00:01
  hmix_del2:
    config_use_mom_del2: true
    config_mom_del2: {{ nu }}
  hmix_del4:
    config_use_mom_del4: false
  forcing:
    config_use_bulk_wind_stress: true
  debug:
    config_disable_vel_explicit_bottom_drag: true
  bottom_drag:
    config_explicit_bottom_drag_coeff: {{ drag }}

mpas-ocean:
  time_integration:
    config_time_integrator: split_explicit_ab2
  io:
    config_write_output_on_startup: false
  lateral_walls:
    config_wall_slip_factor: 0.0
  pressure_gradient:
    config_pressure_gradient_type: pressure_and_zmid
  ALE_vertical_grid:
    config_vert_coord_movement: uniform_stretching
    config_ALE_thickness_proportionality: restingThickness_times_weights
  cvmix:
    config_cvmix_background_scheme: none
    config_use_cvmix_convection: true
  split_explicit_ts:
    config_btr_dt: 0000_00:00:05
  bottom_drag:
    config_bottom_drag_mode: explicit
  forcing:
    config_use_bulk_wind_stress: true
  debug:
    config_disable_vel_coriolis: true
  streams:
    mesh:
      filename_template: init.nc
    input:
      filename_template: init.nc
    restart:
      output_interval: 0000_01:00:00
    forcing:
      filename_template: forcing.nc
      input_interval: initial_only
      type: input
      contents:
      - windStressZonal
      - windStressMeridional
    output:
      type: output
      filename_template: output.nc
      output_interval: 0000_01:00:00
      clobber_mode: truncate
      contents:
      - tracers
      - xtime
      - normalVelocity
      - velocityZonal
      - velocityMeridional
      - layerThickness
      - ssh
      - vertVelocityTop
      - density
      - daysSinceStartOfSim
      - circulation
      - relativeVorticity

Omega:
  TimeIntegration:
    TimeStepper: RungeKutta4
  Tendencies:
    TracerHorzAdvTendencyEnable : false
    TracerDiffTendencyEnable : false
    TracerHyperDiffTendencyEnable : false
  Advection:
    FluxThicknessType: Center
  IOStreams:
    InitialVertCoord:
      UsePointerFile: false
      Filename: init.nc
      Mode: read
      Precision: double
      Freq: 1
      FreqUnits: OnStartup
      UseStartEnd: false
      Contents:
        - InitVertCoord
    InitialState:
      UsePointerFile: false
      Filename: init.nc
      Mode: read
      Precision: double
      Freq: 1
      FreqUnits: OnStartup
      UseStartEnd: false
      Contents:
      - State
      - Base
      - WindStressZonal
      - WindStressMeridional
    RestartRead:
      UsePointerFile: true
      PointerFilename: ocn.pointer
      Mode: read
      Precision: double
      Freq: 1
      FreqUnits: OnStartup
      UseStartEnd: true
      StartTime: 0001-01-01_00:00:01
      EndTime: 99999-12-31_00:00:00
      Contents:
        - Restart
    RestartWrite:
      UsePointerFile: true
      PointerFilename: ocn.pointer
      Filename: ocn.restart.$Y-$M-$D_$h.$m.$s
      Mode: write
      IfExists: replace
      Precision: double
      Freq: 6
      FreqUnits: months
      UseStartEnd: false
      Contents:
        - Restart
    History:
      UsePointerFile: false
      Filename: output.nc
      Mode: write
      IfExists: append
      Precision: double
      Freq: 1
      FreqUnits: hours
      UseStartEnd: false
      Contents:
      - AuxiliaryState
      - State
      - SshCell
      FileFreq: 9999
      FileFreqUnits: years
