mpas-ocean:
  streams:
    coeffs_reconstruct:
      type: output
      filename_template: coeffs_reconstruct.nc
      output_interval: 0000_00:00:01
      clobber_mode: truncate
      contents:
      - coeffs_reconstruct
